### ISSUE TITLE
strange PHP parsing issue

### ISSUE THREAD

**Issue by someson** [TicketSwap/phpstan-error-formatter#3] opened 2024-09-09 09:18 UTC
After installing:
```
In Resolver.php line 349:

  Service 'errorFormatter.ticketswap': syntax error, unexpected identifier "FORMAT", expecting "="


In TicketSwapErrorFormatter.php line 16:

  syntax error, unexpected identifier "FORMAT", expecting "="
```

full trace:
```
❯ docker-compose exec php-app vendor/bin/phpstan -v
Note: Using configuration file /var/www/phpstan.neon.

In Resolver.php line 349:

  [_PHPStan_9815bbba4\Nette\DI\ServiceCreationException]
  Service 'errorFormatter.ticketswap': syntax error, unexpected identifier "FORMAT", expecting "="


Exception trace:
  at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php:349
 _PHPStan_9815bbba4\Nette\DI\Resolver->completeException() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php:62
 _PHPStan_9815bbba4\Nette\DI\Resolver->resolveDefinition() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerBuilder.php:235
 _PHPStan_9815bbba4\Nette\DI\ContainerBuilder->resolve() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php:198
 _PHPStan_9815bbba4\Nette\DI\Compiler->processBeforeCompile() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php:159
 _PHPStan_9815bbba4\Nette\DI\Compiler->compile() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php:99
 _PHPStan_9815bbba4\Nette\DI\ContainerLoader->generate() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php:65
 _PHPStan_9815bbba4\Nette\DI\ContainerLoader->loadFile() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php:34
 _PHPStan_9815bbba4\Nette\DI\ContainerLoader->load() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/Configurator.php:56
 PHPStan\DependencyInjection\Configurator->loadContainer() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/bootstrap/src/Bootstrap/Configurator.php:177
 _PHPStan_9815bbba4\Nette\Bootstrap\Configurator->createContainer() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/Configurator.php:68
 PHPStan\DependencyInjection\Configurator->createContainer() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/ContainerFactory.php:125
 PHPStan\DependencyInjection\ContainerFactory->create() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Command/CommandHelper.php:284
 PHPStan\Command\CommandHelper::begin() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php:126
 PHPStan\Command\AnalyseCommand->execute() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php:259
 _PHPStan_9815bbba4\Symfony\Component\Console\Command\Command->run() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php:870
 _PHPStan_9815bbba4\Symfony\Component\Console\Application->doRunCommand() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php:261
 _PHPStan_9815bbba4\Symfony\Component\Console\Application->doRun() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php:157
 _PHPStan_9815bbba4\Symfony\Component\Console\Application->run() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan:124
 _PHPStan_9815bbba4\{closure}() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan:125
 require() at /var/www/vendor/phpstan/phpstan/phpstan:8
 include() at /var/www/vendor/bin/phpstan:119

In TicketSwapErrorFormatter.php line 16:

  [ParseError]
  syntax error, unexpected identifier "FORMAT", expecting "="


Exception trace:
  at /var/www/vendor/ticketswap/phpstan-error-formatter/src/TicketSwapErrorFormatter.php:16
 Composer\Autoload\{closure}() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/composer/ClassLoader.php:427
 Composer\Autoload\ClassLoader->loadClass() at n/a:n/a
 class_exists() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php:114
 _PHPStan_9815bbba4\Nette\DI\Resolver->resolveEntityType() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Definitions/ServiceDefinition.php:116
 _PHPStan_9815bbba4\Nette\DI\Definitions\ServiceDefinition->resolveType() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php:57
 _PHPStan_9815bbba4\Nette\DI\Resolver->resolveDefinition() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerBuilder.php:235
 _PHPStan_9815bbba4\Nette\DI\ContainerBuilder->resolve() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php:198
 _PHPStan_9815bbba4\Nette\DI\Compiler->processBeforeCompile() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php:159
 _PHPStan_9815bbba4\Nette\DI\Compiler->compile() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php:99
 _PHPStan_9815bbba4\Nette\DI\ContainerLoader->generate() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php:65
 _PHPStan_9815bbba4\Nette\DI\ContainerLoader->loadFile() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php:34
 _PHPStan_9815bbba4\Nette\DI\ContainerLoader->load() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/Configurator.php:56
 PHPStan\DependencyInjection\Configurator->loadContainer() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/bootstrap/src/Bootstrap/Configurator.php:177
 _PHPStan_9815bbba4\Nette\Bootstrap\Configurator->createContainer() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/Configurator.php:68
 PHPStan\DependencyInjection\Configurator->createContainer() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/ContainerFactory.php:125
 PHPStan\DependencyInjection\ContainerFactory->create() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Command/CommandHelper.php:284
 PHPStan\Command\CommandHelper::begin() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php:126
 PHPStan\Command\AnalyseCommand->execute() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php:259
 _PHPStan_9815bbba4\Symfony\Component\Console\Command\Command->run() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php:870
 _PHPStan_9815bbba4\Symfony\Component\Console\Application->doRunCommand() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php:261
 _PHPStan_9815bbba4\Symfony\Component\Console\Application->doRun() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php:157
 _PHPStan_9815bbba4\Symfony\Component\Console\Application->run() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan:124
 _PHPStan_9815bbba4\{closure}() at phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan:125
 require() at /var/www/vendor/phpstan/phpstan/phpstan:8
 include() at /var/www/vendor/bin/phpstan:119

analyse [-c|--configuration CONFIGURATION] [-l|--level LEVEL] [--no-progress] [--debug] [-a|--autoload-file AUTOLOAD-FILE] [--error-format ERROR-FORMAT] [-b|--generate-baseline [GENERATE-BASELINE]] [--allow-empty-baseline] [--memory-limit MEMORY-LIMIT] [--xdebug] [--fix] [--watch] [--pro] [--fail-without-result-cache] [--] [<paths>...]
```

i didn't look deeper, just removed the composer extension and everything was fine again.

**Comment by someson** [comment] 2024-09-09 09:22
my `composer.json`:
```
{
    "name": "[REDUCTED]",
    "type": "project",
    "license": "MIT",
    "minimum-stability": "stable",
    "prefer-stable": true,
    "require": {
        "php": ">=8.2",
        "ext-ctype": "*",
        "ext-dom": "*",
        "ext-iconv": "*",
        "ext-json": "*",
        "ext-mbstring": "*",
        "ext-zip": "*",
        "cuyz/valinor": "*",
        "doctrine/doctrine-bundle": "^2.10",
        "doctrine/doctrine-migrations-bundle": "^3.2",
        "doctrine/orm": "^2.15",
        "dukecity/doctrineextensions": "^2.0",
        "guzzlehttp/guzzle": "*",
        "illuminate/support": "^11.1",
        "manticoresoftware/manticoresearch-php": "^3.0",
        "nelmio/cors-bundle": "^2.3",
        "phpdocumentor/reflection-docblock": "^5.3",
        "phpdocumentor/type-resolver": "^1.7",
        "phpstan/phpdoc-parser": "^1.24",
        "ramsey/uuid-doctrine": "^2.0",
        "shipmonk/doctrine-mysql-index-hints": "^2.1",
        "symfony/amqp-messenger": "7.1.*",
        "symfony/asset": "7.1.*",
        "symfony/asset-mapper": "7.1.*",
        "symfony/cache": "7.1.*",
        "symfony/console": "7.1.*",
        "symfony/css-selector": "7.1.*",
        "symfony/doctrine-messenger": "7.1.*",
        "symfony/dom-crawler": "7.1.*",
        "symfony/dotenv": "7.1.*",
        "symfony/expression-language": "7.1.*",
        "symfony/flex": "^2",
        "symfony/form": "7.1.*",
        "symfony/framework-bundle": "7.1.*",
        "symfony/http-client": "7.1.*",
        "symfony/intl": "7.1.*",
        "symfony/mailer": "7.1.*",
        "symfony/mime": "7.1.*",
        "symfony/monolog-bundle": "^3.0",
        "symfony/notifier": "7.1.*",
        "symfony/process": "7.1.*",
        "symfony/property-access": "7.1.*",
        "symfony/property-info": "7.1.*",
        "symfony/runtime": "7.1.*",
        "symfony/security-bundle": "7.1.*",
        "symfony/serializer": "7.1.*",
        "symfony/stimulus-bundle": "^2.18",
        "symfony/stopwatch": "7.1.*",
        "symfony/string": "7.1.*",
        "symfony/translation": "7.1.*",
        "symfony/twig-bundle": "7.1.*",
        "symfony/ux-live-component": "^2.18",
        "symfony/validator": "7.1.*",
        "symfony/web-link": "7.1.*",
        "symfony/yaml": "7.1.*",
        "twig/extra-bundle": "^3.0",
        "twig/twig": "^3.0"
    },
    "require-dev": {
        "phpstan/extension-installer": "^1.3",
        "phpstan/phpstan": "^1.12",
        "phpstan/phpstan-doctrine": "^1.3",
        "phpstan/phpstan-phpunit": "^1.3",
        "phpunit/phpunit": "^9.6",
        "symfony/browser-kit": "7.1.*",
        "symfony/debug-bundle": "7.1.*",
        "symfony/maker-bundle": "^1.0",
        "symfony/phpunit-bridge": "7.1.*",
        "symfony/web-profiler-bundle": "7.1.*"
    },
    "config": {
        "allow-plugins": {
            "php-http/discovery": true,
            "symfony/flex": true,
            "symfony/runtime": true,
            "phpstan/extension-installer": true
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php73": "*",
        "symfony/polyfill-php74": "*",
        "symfony/polyfill-php80": "*",
        "symfony/polyfill-php81": "*",
        "symfony/polyfill-php82": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd",
            "importmap:install": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "7.1.*"
        }
    }
}
```

**Comment by ruudk** [comment] 2024-09-09 09:32
Thanks @someson. I see what the problem is and will fix it soon!

**Comment by ruudk** [comment] 2024-09-09 10:13
Should be fixed with https://github.com/TicketSwap/phpstan-error-formatter/releases/tag/1.0.2

Thanks for your report.

**Closed by ruudk** 2024-09-09 10:13 UTC
